// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ApiDoble.Models;
//
//    var random = Random.FromJson(jsonString);

namespace ApiDoble.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Random
    {
        [JsonProperty("DateAndTime")]
        public DateTimeOffset DateAndTime { get; set; }

        [JsonProperty("Random")]
        public long RandomNumber { get; set; }
    }

    public partial class Random
    {
        public static Random FromJson(string json) => JsonConvert.DeserializeObject<Random>(json, ApiDoble.Models.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Random self) => JsonConvert.SerializeObject(self, ApiDoble.Models.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
